In [5]:
import numpy as np
x=np.zeros(10)
a = np.asarray(x)
print('第一个数组:')
print(a)
print('\n')
print('第二个数组:')
b = np.array([0,0,0,0,1,0,0,0,0,0])
print (b)
print('\n')
print('两个数组相减加:')
print(np.add(a,b))

第一个数组:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


第二个数组:
[0 0 0 0 1 0 0 0 0 0]


两个数组相减加:
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [8]:
import numpy as np
x = np.empty([5,3],dtype = int)
print (x)
y = np.empty([3,2],dtype = int)
print (y)
print('两个数组相乘:')
print(np.multiply(a,b))

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
[[-1230198000 -1230210888]
 [-1230197960 -1227373120]
 [-1230197920 -1230197880]]
两个数组相乘:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [17]:

a = [11,-13,17,-17,7,24,77,47,-288]  #测试的案例
b = len(a)                           #队列长度
for i in range(b):
    for j in range(b-i-1):           #设置循环次数
        if a[j]>a[j+1]:
            a[j],a[j+1]=a[j+1],a[j]
print(a)

[-288, -17, -13, 7, 11, 17, 24, 47, 77]


In [48]:
import numpy as np
x = np.empty([10,10],dtype = int)

print ('以F（按列）风格顺序展开从小到大的数组: ')
a=x.flatten(order = 'F')
b = len(a)                           #队列长度
for i in range(b):
    for j in range(b-i-1):           #设置循环次数
        if a[j]>a[j+1]:
            a[j],a[j+1]=a[j+1],a[j]
print (a)
print ('\n')
print ('输出最小值')
print (np.min(a))
print ('\n')
print ('输出最大值')
print (np.max(a))

以F（按列）风格顺序展开从小到大的数组: 
[-1325457376 -1325455880 -1325455792 -1325455704 -1325455088 -1325455000
 -1325454912 -1325454824 -1325454384 -1325454296 -1325454208 -1325454120
 -1325454032 -1325453944 -1325453680 -1325453592 -1325453504 -1325453416
 -1325451860 -1325436896 -1325436808 -1325436720 -1325436632 -1325436456
 -1325436280 -1325436192 -1325436104 -1325436016 -1325435928 -1325435752
 -1325435224 -1325435048 -1325434960 -1325434872 -1325434696 -1325434608
 -1325434432 -1325434344 -1325434256 -1325434168 -1325434080 -1325433992
 -1325433904 -1325433728 -1325433552 -1325433464 -1325433376 -1325433288
 -1325433200 -1325433112 -1325432320 -1325431720 -1325431400 -1325431068
 -1325431028 -1325419412 -1325419380 -1325419252 -1325419220 -1325419188
 -1325419156 -1325419124 -1325419092 -1325419060 -1325419028 -1325418996
 -1325418964 -1325418932 -1325418900 -1325418868 -1325418836 -1325418804
 -1325418772 -1325418740 -1325418708 -1325411972 -1325408048 -1325407960
 -1324091928 -1324068352 -132

In [49]:
a = np.array([1,2,0,0,4,0])
print(np.where(a==0))


(array([2, 3, 5], dtype=int32),)


In [50]:
a = np.array([[3,3.2],[3.5,3.6]])
b = np.array([118.4,135.2])
c = np.linalg.inv(a)
print('\n')
print('两个数组相乘:')
print(np.multiply(c,b))



两个数组相乘:
[[-1065.6  1081.6]
 [ 1036.  -1014. ]]
